[jobs.build-clang]
command = ["ninja", "-C", "example-cpp/build-clang"]
need_stdout = true
analyzer = "cpp"
env.CLICOLOR_FORCE = "1"

[jobs.build-gcc]
command = ["ninja", "-C", "example-cpp/build-gcc"]
need_stdout = true
analyzer = "cpp"
env.CLICOLOR_FORCE = "1"
